name: terraform-provider-zonefile Release Test
on:
  workflow_dispatch: {}
jobs:
  goreleaser-snapshot:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Allow goreleaser to access older tag information.
    - uses: actions/setup-go@v5
      with:
        go-version: "1.23"
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        args: release --clean --snapshot --skip=sign
